# 机械特性-断路器模块
mb:
  # 基础配置
  base:
    type: 3 # 设备相数
    timeAllow: 3 # 文件匹配允许的时间差/s
    rate: 5 # 采样率/KHz
  # 诊断配置
  diagnose:
    tripMax: 172 # 行程最大阈值
    tripMin: 168 # 行程最小阈值
    openTMax: 30 # 分闸时间最大阈值
    openTmeMin: 24 # 分闸时间最小阈值
    closeTMax: 100 # 合闸时间最大阈值
    closeTMin: 15 # 合闸时间最小阈值
    openVMax: 6 # 分闸速度最大阈值
    openVMin: 5 # 分闸速度最小阈值
    closeVMax: 4 # 合闸速度最大阈值
    closeVMin: 3 # 合闸速度最小阈值
    openCTMax: 40 # 分带电时间阈值
    closeCTMax: 70 # 合带电时间阈值
    openCMax: 1 # 分电流阈值
    closeCMax: 1 # 合电流阈值
  # A相配置
  A:
    # 行程
    trip:
      dir: 1 # 行程方向 1正 0反
      openVirC: 0.7404 # 分闸虚拟断口
      closeVirC: 0.7927 # 合闸虚拟断口
      openVC: 1 # 分闸速度系数
      closeVC: 1 # 合闸速度系数
      tripC: 2.8231 # 行程曲线系数
      openC: 2.838 # 分闸行程系数
      closeC: 2.804 # 合闸行程系数
      pulse: 4096 # 每转脉冲数
    # 电流
    cur:
      dotCount: 3000 # 电流传感器采集点数
      openC: 1.467 # 分闸电流系数
      closeC: 1.383 # 合闸电流系数
      secOpenC: 1 # 副分电流系数
  # B相配置
  B:
    # 行程
    trip:
      dir: 1 # 行程方向 1正 0反
      openVirC: 0.7359 # 分闸虚拟断口
      closeVirC: 0.7713 # 合闸虚拟断口
      openVC: 1 # 分闸速度系数
      closeVC: 1 # 合闸速度系数
      tripC: 2.8561 # 行程曲线系数
      openC: 2.87 # 分闸行程系数
      closeC: 2.842 # 合闸行程系数
      pulse: 4096 # 每转脉冲数
    # 电流
    cur:
      dotCount: 3000 # 电流传感器采集点数
      openC: 1.38 # 分闸电流系数
      closeC: 1.333 # 合闸电流系数
      secOpenC: 1 # 副分电流系数
  # C相配置
  C:
    # 行程
    trip:
      dir: 1 # 行程方向 1正 0反
      openVirC: 0.7417 # 分闸虚拟断口
      closeVirC: 0.7764 # 合闸虚拟断口
      openVC: 1 # 分闸速度系数
      closeVC: 1 # 合闸速度系数
      tripC: 2.8139 # 行程曲线系数
      openC: 2.851 # 分闸行程系数
      closeC: 2.775 # 合闸行程系数
      pulse: 4096 # 每转脉冲数
    # 电流
    cur:
      dotCount: 3000 # 电流传感器采集点数
      openC: 1.245 # 分闸电流系数
      closeC: 1.333 # 合闸电流系数
      secOpenC: 1 # 副分电流系数

# 机械特性-隔离开关模块
ms:
  # 电机电流
  cur:
    rate: 2 # 采样率/KHz
    dotCount: 3000 # 每路采集点数
    oneC: 1 # QSF1电流系数
    twoC: 1 # QSF2电流系数
    threeC: 1 # QS3电流系数
    max: 15 # 最大工作电流

# 储能模块
es:
  # 基础配置
  base:
    type: 3 # 设备相数
    rate: 1 # 采样率/KHz
    timeAllow: 20 # 文件匹配允许的时间差/s
  # 弹簧
  spring:
    dotCount: 6000 # 每路点数
    openC: 1 # 分闸弹簧压力系数
    closeC: 1 # 合闸弹簧压力系数
    closeMax: 15 # 合弹簧压力阈值
  # 电流
  cur:
    dotCount: 6000 # 每路采集点数
    aC: 1 # 储能A相电机电流系数
    bC: 1 # 储能B相电机电流系数
    cC: 1 # 储能C相电机电流系数
    max: 15 # 储能电机电流阈值

# 振动模块
vb:
  # 断路器振动
  breaker:
    rate: 20 # 采样率/KHz
    dotCount: 3996 # 采集点数
    aC: 1 # 加速度系数
    ampC: 1 # 幅值系数
    fC: 1 # 频率系数
  # 母线振动
  bus:
    rate: 20 # 采样率/KHz
    dotCount: 3996 # 每轴采集点数
    aC: 1 # 加速度系数
    ampC: 1 # 幅值系数
    fC: 1 # 频率系数

# 气体模块
gas:
  # 断路器气室
  breaker:
    lowWarn: 0.52 # 低气压报警阈值: 0.52
    lowLock: 0.5 # 低气压闭锁阈值: 0.5
  # 其他气室
  other:
    lowWarn: 0.4 # 低气压报警阈值: 0.4

# 环境模块
ev:
  tempMax: 70 # 温度高温阈值
  tempMin: 5 # 温度低温阈值
  hum: 80 # 湿度阈值
