# 气体模块
gas:
  # 断路器气室
  breaker:
    lowWarn: 0.52 # 低气压报警阈值: 0.52
    lowLock: 0.5 # 低气压闭锁阈值: 0.5
  # 其他气室
  other:
    lowWarn: 0.4 # 低气压报警阈值: 0.4

# 环境模块
env:
  tempMax: 70 # 温度高温阈值
  tempMin: 5 # 温度低温阈值
  hum: 80 # 湿度阈值

# 机械特性-隔离开关模块
ms:
  # 电机电流
  cur:
    max: 15 # 最大工作电流

# 机械特性-断路器模块
mb:
  tripMax: 172 # 行程最大阈值
  tripMin: 168 # 行程最小阈值
  openTMax: 30 # 分闸时间最大阈值
  openTmeMin: 24 # 分闸时间最小阈值
  closeTMax: 100 # 合闸时间最大阈值
  closeTMin: 15 # 合闸时间最小阈值
  openVMax: 6 # 分闸速度最大阈值
  openVMin: 5 # 分闸速度最小阈值
  closeVMax: 4 # 合闸速度最大阈值
  closeVMin: 3 # 合闸速度最小阈值
  openCTMax: 40 # 分带电时间阈值
  closeCTMax: 70 # 合带电时间阈值
  openCMax: 1 # 分电流阈值
  closeCMax: 1 # 合电流阈值


# 储能模块
es:
  # 弹簧
  spring:
    closeMax: 15 # 合弹簧压力阈值
  # 电流
  cur:
    max: 15 # 储能电机电流阈值